include theos/makefiles/common.mk

TOOL_NAME = speakevent
speakevent_FILES = main.mm
speakevent_PRIVATE_FRAMEWORKS = AppSupport

export TARGET=iphone:latest:5.0
export ARCHS = armv7 arm64

include $(THEOS_MAKE_PATH)/tool.mk
